// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7Ex9S6lP7bFYGUuVfSbedfA_h4OD0e1k',
    appId: '1:930813567969:web:e36d433058ef266e9428a0',
    messagingSenderId: '930813567969',
    projectId: 'saveup-5e005',
    authDomain: 'saveup-5e005.firebaseapp.com',
    storageBucket: 'saveup-5e005.appspot.com',
    measurementId: 'G-KLXZEC73GK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbhethrTKV2JflI0gXzbFCJnMuUprVNsk',
    appId: '1:930813567969:android:9e9da5c714bb3a559428a0',
    messagingSenderId: '930813567969',
    projectId: 'saveup-5e005',
    storageBucket: 'saveup-5e005.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNX4RnO4uyNMRNGEWkVUCNUaqjr_DTyuM',
    appId: '1:930813567969:ios:f421f10798766d799428a0',
    messagingSenderId: '930813567969',
    projectId: 'saveup-5e005',
    storageBucket: 'saveup-5e005.appspot.com',
    iosBundleId: 'com.example.saveup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNX4RnO4uyNMRNGEWkVUCNUaqjr_DTyuM',
    appId: '1:930813567969:ios:530598794f96104f9428a0',
    messagingSenderId: '930813567969',
    projectId: 'saveup-5e005',
    storageBucket: 'saveup-5e005.appspot.com',
    iosBundleId: 'com.example.saveup.RunnerTests',
  );
}
